### ISSUE TITLE
ourboros update (dependabot alert)

### ISSUE THREAD

**Issue by elpiel** [embedded-graphics/simulator#50]
- Version of embedded-graphics-simulator in use (if applicable): 0.5
- Version of embedded-graphics in use (if applicable): 0.8

> Ouroboros is Unsound
> 
> Upgrade ouroboros to version 0.16.0 or later. For example:
> 
```
[dependencies]
ouroboros = "0.16.0"

[dev-dependencies]
ouroboros = "0.16.0"
```
> 
> In 0.15.0 and prior, Ouroboros works internally by creating a struct where all uses of 'this are replaced by 'static. However, a recent addition to Miri checks that references passed to functions are valid during the entire execution of the function, even when those references are passed inside a struct. This poses an issue for dropping self-referencing values, as the reference becomes invalid during the dropping process. Effectively, since self-referencing structs are not allowed in vanilla Rust, there is no allowance for dropping data during a function that has also been given a reference to that data. There's usually no way to pass a and &a to the same function.
> 
> A fix was attempted, where the struct would be turned in to a raw byte array and only transformed back into the underlying data type inside each function. This is allowable as a reference can be created and die over the body of a function, as long as the reference was created inside the function. However, this is also not sound if the original struct contains padding. There is no way to initialize padding bytes to a known value that Miri will accept, so when it is cast to an array some of the bytes contain uninitialized values. This is not acceptable (despite the fact that these bytes are never read) due to the potential for optimizations that may read from the uninitialized bytes. Besides which, this fix does not allow for template or constant parameters as there is no way to check the size of a templated type without giving specific, concrete values for the template parameters.
> 
> The final solution was to use this fix while wrapping the raw byte array in MaybeUninit<>.

**Comment by tommy-gilligan** [comment]
I'm getting the same thing.
You can get around it by using an unreleased version of simulator.
Something like this in your `Cargo.toml`
```
embedded-graphics-simulator = { git = "https://github.com/embedded-graphics/simulator.git" }
```

**Comment by elpiel** [comment]
Yeah, it's just better to bump dep. and also release a new minor?! version

**Comment by rfuest** [comment]
I was planning to release a new version to fix this issue, but couldn't do it because of the reason I mentioned in #52.

**Comment by elpiel** [comment]
@jamwaffles it appears that @rfuest still doesn't have sufficient permissions to merge PRs.

Would you mind taking a look please?

Also I'm not sure who has permission to publish new version to crates.io so this is also something we can take a look at now.

**Comment by jamwaffles** [comment]
@rfuest sorry for the delay. I've added the e-g-core-team group to those who are allowed to bypass branch protections. This should also allow you to do a release as well as merge #52.

**Comment by rfuest** [comment]
Creating the release didn't work quite as smoothly as I had hoped, but version 0.6.0 is now released. I've released it as 0.6.0 instead of 0.5.1, because I updated the `image` crate dependency, which is part of our crates API, but there shouldn't be any breaking changes for most users of the simulator.

**Comment by jamwaffles** [comment]
I'm glad it worked at some level though. What went wrong specifically? Also, don't forget to draft a Github release as per `releasing.md`.

**Comment by jamwaffles** [comment]
Oop, just got the email. Ignore the latter part.

**Comment by rfuest** [comment]
> Oop, just got the email. Ignore the latter part.

Thanks for the reminder anyway, because I did almost forget that part.

> What went wrong specifically?

At first I did forget to add the `push-remote` parameter, which made `cargo-release` push the commit and tag to my fork instead of the upstream repo. When I tried to manually push the commit and tag to upstream I did get this error:

![grafik](https://github.com/embedded-graphics/simulator/assets/226123/14805e15-3fc2-4af9-b379-8c4df2304ce9)

(Sorry that it's partially in German, but at least the important parts are in English)

I don't think that it would have worked better if I hadn't forgotten to set the remote for `cargo-release` and I don't know if there is a way to bypass the protection without going through a PR.

**Comment by jamwaffles** [comment]
Thanks for the screenshot. I had another look through the repo settings and didn't find anywhere with my username in it specifically that would let me push to `master` but nobody else. I'm not sure there's anything else I can do, but whatever happens I'd like to remove myself as the SPoF for releases. Sounds like we're about 90% the way there...

**Comment by rfuest** [comment]
Which role did you assign to me or the e-g-core team? According to this page https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization pushing to protected branches needs at least the Maintain level. But I guess that this is the role you assigned.

Can you try to push some trivial change to `master` to see if it works for you, just to make sure that it is a permissions problem and not something else? You could, for example, add the missing `### Changed` to the changelog for the 0.6.0 release.

**Comment by jamwaffles** [comment]
e-g-core team does have the role "maintain" so that's sorted.

I fixed the changelog and pushed:

```
❯ git push
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 343 bytes | 343.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: Bypassed rule violations for refs/heads/master:
remote: 
remote: - Changes must be made through a pull request.
remote: 
remote: - Required status check "build_all" is expected.
remote: 
To github.com:embedded-graphics/simulator.git
   819583a..5a24d53  master -> master
```

This is a fresh checkout with:

```
❯ git remote -v
origin  git@github.com:embedded-graphics/simulator.git (fetch)
origin  git@github.com:embedded-graphics/simulator.git (push)
```

**Comment by rfuest** [comment]
How did you allow me to bypass the review requirement for PRs? According to the list I linked above this also requires the `Admin` role.

**Comment by jamwaffles** [comment]
I believe I turned this option on:

![image](https://github.com/embedded-graphics/simulator/assets/800791/0a38c1c1-9823-4ffb-9002-e7efecf397fa)

**Comment by rfuest** [comment]
I think that it might be possible to get the permissions right using the new rulesets feature, instead of the branch protection settings. Here is a post that describes how this could be configured: https://github.com/orgs/community/discussions/43460#discussioncomment-6310318

If this doesn't work the only other alternative I can think of would be to give the core team admin rights. Or we leave it as is, which makes it harder, but not impossible, for me to create releases and kind of defeats the purpose of release automation in the first place.

**Comment by elpiel** [comment]
I guess this can be closed?

 The dependency was updated in the latest release
